## Импорты

In [111]:
import numpy as np
import pandas as pd
import plotly.express as px

# Задание 13

In [112]:
df = pd.read_csv('/content/Smartphones_cleaned_dataset.csv')

In [113]:
df.head(10)

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
0,oneplus,OnePlus 11 5G,54999,89.0,True,True,False,snapdragon,8.0,3.20,...,120,3,1.0,android,50.0,16.0,0,NaN,1440,3216
1,oneplus,OnePlus Nord CE 2 Lite 5G,19989,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,64.0,16.0,1,1024.0,1080,2412
2,samsung,Samsung Galaxy A14 5G,16499,75.0,True,False,False,exynos,8.0,2.40,...,90,3,1.0,android,50.0,13.0,1,1024.0,1080,2408
3,motorola,Motorola Moto G62 5G,14999,81.0,True,False,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,16.0,1,1024.0,1080,2400
4,realme,Realme 10 Pro Plus,24999,82.0,True,False,False,dimensity,8.0,2.60,...,120,3,1.0,android,108.0,16.0,0,NaN,1080,2412
5,samsung,Samsung Galaxy F23 5G (6GB RAM + 128GB),16999,80.0,True,True,False,snapdragon,8.0,2.20,...,120,3,1.0,android,50.0,8.0,1,1024.0,1080,2408
6,apple,Apple iPhone 14,65999,81.0,True,True,False,bionic,6.0,3.22,...,60,2,1.0,ios,12.0,12.0,0,NaN,1170,2532
7,xiaomi,Xiaomi Redmi Note 12 Pro Plus,29999,86.0,True,False,True,dimensity,8.0,2.60,...,120,3,1.0,android,200.0,16.0,0,NaN,1080,2400
8,nothing,Nothing Phone 1,26749,85.0,True,True,False,snapdragon,8.0,2.50,...,120,2,1.0,android,50.0,16.0,0,NaN,1080,2400
9,oneplus,OnePlus Nord 2T 5G,28999,84.0,True,True,False,dimensity,8.0,3.00,...,90,3,1.0,android,50.0,32.0,0,NaN,1080,2400

In [114]:
df.describe(include='all')

,brand_name,model,price,rating,has_5g,has_nfc,has_ir_blaster,processor_brand,num_cores,processor_speed,...,refresh_rate,num_rear_cameras,num_front_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,extended_upto,resolution_width,resolution_height
count,980,980,980.000000,879.000000,980,980,980,960,974.000000,938.000000,...,980.000000,980.000000,976.000000,966,980.000000,975.000000,980.000000,500.000000,980.000000,980.000000
unique,46,980,NaN,NaN,2,2,2,13,NaN,NaN,...,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
top,xiaomi,Samsung Galaxy M52s 5G,NaN,NaN,True,False,False,snapdragon,NaN,NaN,...,NaN,NaN,NaN,android,NaN,NaN,NaN,NaN,NaN,NaN
freq,134,1,NaN,NaN,549,587,821,413,NaN,NaN,...,NaN,NaN,NaN,909,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,32520.504082,78.258248,NaN,NaN,NaN,NaN,7.772074,2.427217,...,92.256122,2.814286,1.029713,NaN,50.319286,16.589128,0.630612,736.064000,1075.852041,2214.663265
std,NaN,NaN,39531.812669,7.402854,NaN,NaN,NaN,NaN,0.836845,0.464090,...,28.988052,0.776441,0.169882,NaN,33.000968,10.876802,0.482885,366.894911,290.164931,516.484254
min,NaN,NaN,3499.000000,60.000000,NaN,NaN,NaN,NaN,4.000000,1.200000,...,60.000000,1.000000,1.000000,NaN,2.000000,0.300000,0.000000,32.000000,480.000000,480.000000
25%,NaN,NaN,12999.000000,74.000000,NaN,NaN,NaN,NaN,8.000000,2.050000,...,60.000000,2.000000,1.000000,NaN,24.000000,8.000000,0.000000,512.000000,1080.000000,1612.000000
50%,NaN,NaN,19994.500000,80.000000,NaN,NaN,NaN,NaN,8.000000,2.300000,...,90.000000,3.000000,1.000000,NaN,50.000000,16.000000,1.000000,1024.000000,1080.000000,2400.000000
75%,NaN,NaN,35491.500000,84.000000,NaN,NaN,NaN,NaN,8.000000,2.840000,...,120.000000,3.000000,1.000000,NaN,64.000000,16.000000,1.000000,1024.000000,1080.000000,2408.000000
max,NaN,NaN,650000.000000,89.000000,NaN,NaN,NaN,NaN,8.000000,3.220000,...,240.000000,4.000000,2.000000,NaN,200.000000,60.000000,1.000000,2048.000000,2460.000000,3840.000000

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 980 entries, 0 to 979
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   brand_name                 980 non-null    object
 1   model                      980 non-null    object
 2   price                      980 non-null    int64
 3   rating                     879 non-null    float64
 4   has_5g                     980 non-null    bool
 5   has_nfc                    980 non-null    bool
 6   has_ir_blaster             980 non-null    bool
 7   processor_brand            960 non-null    object
 8   num_cores                  974 non-null    float64
 9   processor_speed            938 non-null    float64
 10  battery_capacity           969 non-null    float64
 11  fast_charging_available    980 non-null    int64
 12  fast_charging              769 non-null    float64
 13  ram_capacity               980 non-null    int64
 14  internal_memory            980 non-null    int64
 15  screen_size                980 non-null    float64
 16  refresh_rate               980 non-null    int64
 17  num_rear_cameras           980 non-null    int64
 18  num_front_cameras          976 non-null    float64
 19  os                         966 non-null    object
 20  primary_camera_rear        980 non-null    float64
 21  primary_camera_front       975 non-null    float64
 22  extended_memory_available  980 non-null    int64
 23  extended_upto              500 non-null    float64
 24  resolution_width           980 non-null    int64
 25  resolution_height          980 non-null    int64
dtypes: bool(3), float64(10), int64(9), object(4)
memory usage: 179.1+ KB

## А)

В таблице есть пропуски в столбцах:
+ `rating`
+ `num_cores`
+ `processor_speed`
+ `battery_capacity`
+ `fast_charging`
+ `processor_brand`
+ `num_front_cameras`
+ `os`
+ `primary_camera_front`
+ `extended_upto`

Чем заполнять:
+ `rating`, `processor_speed`, `battery_capacity`, `primary_camera_front` - медианой (можно по группам, например brand_name)
+ `num_cores`, `num_front_cameras`, `processor_brand`, `os` - модой
+ `fast_charging`, `extended_upto` - скорее всего, NaN означает отсутствие функции (связаны с fast_charging_available и extended_memory_available), можно заполнить нулями

## Б)

In [116]:
df['price'].median()

19994.5

Ответ: 19994.5

## В)

In [117]:
len(df[df['has_nfc'] == True])

393

Ответ: 393

## Г)

In [118]:
len(df[(df['rating'] > 85) & (df['screen_size'] > 6.5)])

111

Ответ: 111

## Д)

In [119]:
df[df['fast_charging_available'] == 1]['battery_capacity'].mean()

np.float64(4869.436081242533)

Ответ: 4869

## Е)

In [120]:
df[df['num_rear_cameras'] == 3]['internal_memory'].max()

1024

Ответ: 1024

## Ж)

In [121]:
df.groupby('brand_name')['price'].mean()

brand_name
apple         95966.521739
asus          74709.428571
blackview      8990.000000
blu           14990.000000
cat           14999.000000
cola          14999.000000
doogee        30499.000000
duoqin         9990.000000
gionee         6896.000000
google        44332.571429
honor         30301.846154
huawei        80177.250000
ikall          7632.333333
infinix       14664.793103
iqoo          30301.875000
itel           5811.000000
jio            7159.250000
lava          11246.750000
leeco         10999.000000
leitz        124990.000000
lenovo        53494.500000
letv           6165.666667
lg            63329.333333
lyf            3940.000000
micromax       6929.333333
motorola      24099.923077
nokia         24630.769231
nothing       31195.400000
nubia         49827.833333
oneplus       35858.571429
oppo          29650.034091
oukitel       26293.000000
poco          18479.195122
realme        17461.422680
redmi         15665.666667
royole       129999.000000
samsung       36843.030303
sharp         59990.000000
sony          60570.666667
tcl            8990.000000
tecno         14545.363636
tesla         69999.000000
vertu        650000.000000
vivo          26782.387387
xiaomi        27961.111940
zte           40994.500000
Name: price, dtype: float64

# Задание 14

## А)

In [122]:
fig_1 = px.scatter(
    df,
    x='rating',
    y='price',
    title='Зависимость цены смартфона от рейтинга',
    hover_data=['model'],
    color='rating'
    )

fig_1.update_yaxes(type='log')

fig_1.show()

## Б)

In [125]:
labels = {
    0: 'Нет 5G и NFC',
    1: 'Есть NFC, но нет 5G',
    2: 'Есть 5G, но нет NFC',
    3: 'Есть 5G и NFC'
}

conditions = [
    (df['has_5g'] == 0) & (df['has_nfc'] == 0),
    (df['has_5g'] == 0) & (df['has_nfc'] == 1),
    (df['has_5g'] == 1) & (df['has_nfc'] == 0),
    (df['has_5g'] == 1) & (df['has_nfc'] == 1)
]

df['category'] = np.select(conditions, labels.values(), default='Неизвестно')

summary = df.groupby('category', as_index=False)['battery_capacity'].mean()

fig_2 = px.bar(
    summary,
    x='category',
    y='battery_capacity',
    title='Влияние наличия 5G и NFC на среднюю ёмкость аккумулятора',
    labels={
        'category': 'Комбинация признаков',
        'battery_capacity': 'Средняя ёмкость, мАч'
    }
)

fig_2.show()