# Импорты

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

# Задание 13

In [2]:
df = pd.read_csv('/content/medical_insurance.csv')

In [3]:
df.head(10)

,age,gender,bmi,children,discount_eligibility,region,expenses,premium
0,19,female,27.9,0,yes,southwest,16884.92,168.8492
1,18,male,33.8,1,no,southeast,1725.55,17.2555
2,28,male,33.0,3,no,southeast,4449.46,44.4946
3,33,male,22.7,0,no,northwest,21984.47,439.6894
4,32,male,28.9,0,no,northwest,3866.86,77.3372
5,31,female,25.7,0,no,southeast,3756.62,75.1324
6,46,female,33.4,1,no,southeast,8240.59,164.8118
7,37,female,27.7,3,no,northwest,7281.51,145.6302
8,37,male,29.8,2,no,northeast,6406.41,128.1282
9,60,female,25.8,0,no,northwest,28923.14,578.4628

In [5]:
df.describe(include='all')

,age,gender,bmi,children,discount_eligibility,region,expenses,premium
count,1338.000000,1338,1338.000000,1338.000000,1338,1338,1338.000000,1338.000000
unique,NaN,2,NaN,NaN,2,4,NaN,NaN
top,NaN,male,NaN,NaN,no,southeast,NaN,NaN
freq,NaN,676,NaN,NaN,1064,364,NaN,NaN
mean,39.207025,NaN,30.665471,1.094918,NaN,NaN,13270.422414,262.874685
std,14.049960,NaN,6.098382,1.205493,NaN,NaN,12110.011240,292.532178
min,18.000000,NaN,16.000000,0.000000,NaN,NaN,1121.870000,11.218700
25%,27.000000,NaN,26.300000,0.000000,NaN,NaN,4740.287500,87.354250
50%,39.000000,NaN,30.400000,1.000000,NaN,NaN,9382.030000,174.997400
75%,51.000000,NaN,34.700000,2.000000,NaN,NaN,16639.915000,342.908900
max,64.000000,NaN,53.100000,5.000000,NaN,NaN,63770.430000,1983.106400

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   1338 non-null   int64
 1   gender                1338 non-null   object
 2   bmi                   1338 non-null   float64
 3   children              1338 non-null   int64
 4   discount_eligibility  1338 non-null   object
 5   region                1338 non-null   object
 6   expenses              1338 non-null   float64
 7   premium               1338 non-null   float64
dtypes: float64(3), int64(2), object(3)
memory usage: 83.8+ KB

## А)

В таблице нет пропусков в данных.

## Б)

In [18]:
df['bmi'].mean()

np.float64(30.66547085201794)

Ответ: 30.67

## В)

In [13]:
len(df[df['discount_eligibility'] == 'yes'])

274

Ответ: 274

## Г)

In [19]:
len(df[(df['region'] == 'southeast') & (df['age'] > 40)])

172

Ответ: 172

## Д)

In [20]:
df[df['discount_eligibility'] == 'no']['premium'].mean()

np.float64(173.97904342105264)

Ответ: 173

## Е)

In [21]:
df[df['children'] == 3]['expenses'].max()

60021.4

Ответ: 60021.4

## Ж)

In [22]:
df.groupby('region')['premium'].mean()

region
northeast    264.015840
northwest    247.968381
southeast    290.605771
southwest    245.584532
Name: premium, dtype: float64

# Задание 14

## А)

In [52]:
fig_1 = px.histogram(
    df,
    x='bmi',
    y='expenses',
    histfunc='avg',
    title='Зависимость между индексом массы тела и медицинскими рассходами',
    labels={
        'bmi': 'Индекс массы тела (bmi)',
        'expenses': 'Медицинские расходы'
    },
    text_auto='.2s')

fig_1.update_layout(
    yaxis_title="Среднее медицинских расходов",
    xaxis_title="Индекс массы тела"
)

fig_1.show()

## Б)

In [53]:
fig_2 = px.histogram(
    df,
    x='region',
    y='premium',
    title='Распределение страховой премии в зависиомсти от региона',
    text_auto='.2s')

fig_2.update_layout(
    yaxis_title="Сумма страховых премий",
    xaxis_title="Регионы"
)

fig_2.show()